# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matthias/Documents/cpp/bit-nes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matthias/Documents/cpp/bit-nes

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/matthias/Documents/cpp/bit-nes && $(CMAKE_COMMAND) -E cmake_progress_start /home/matthias/Documents/cpp/bit-nes/CMakeFiles /home/matthias/Documents/cpp/bit-nes/bitTGA/CMakeFiles/progress.marks
	cd /home/matthias/Documents/cpp/bit-nes && $(MAKE) -f CMakeFiles/Makefile2 bitTGA/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matthias/Documents/cpp/bit-nes/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/matthias/Documents/cpp/bit-nes && $(MAKE) -f CMakeFiles/Makefile2 bitTGA/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/matthias/Documents/cpp/bit-nes && $(MAKE) -f CMakeFiles/Makefile2 bitTGA/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/matthias/Documents/cpp/bit-nes && $(MAKE) -f CMakeFiles/Makefile2 bitTGA/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/matthias/Documents/cpp/bit-nes && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
bitTGA/CMakeFiles/TGA_Lib.dir/rule:
	cd /home/matthias/Documents/cpp/bit-nes && $(MAKE) -f CMakeFiles/Makefile2 bitTGA/CMakeFiles/TGA_Lib.dir/rule
.PHONY : bitTGA/CMakeFiles/TGA_Lib.dir/rule

# Convenience name for target.
TGA_Lib: bitTGA/CMakeFiles/TGA_Lib.dir/rule

.PHONY : TGA_Lib

# fast build rule for target.
TGA_Lib/fast:
	cd /home/matthias/Documents/cpp/bit-nes && $(MAKE) -f bitTGA/CMakeFiles/TGA_Lib.dir/build.make bitTGA/CMakeFiles/TGA_Lib.dir/build
.PHONY : TGA_Lib/fast

src/TGA_Lib.o: src/TGA_Lib.cc.o

.PHONY : src/TGA_Lib.o

# target to build an object file
src/TGA_Lib.cc.o:
	cd /home/matthias/Documents/cpp/bit-nes && $(MAKE) -f bitTGA/CMakeFiles/TGA_Lib.dir/build.make bitTGA/CMakeFiles/TGA_Lib.dir/src/TGA_Lib.cc.o
.PHONY : src/TGA_Lib.cc.o

src/TGA_Lib.i: src/TGA_Lib.cc.i

.PHONY : src/TGA_Lib.i

# target to preprocess a source file
src/TGA_Lib.cc.i:
	cd /home/matthias/Documents/cpp/bit-nes && $(MAKE) -f bitTGA/CMakeFiles/TGA_Lib.dir/build.make bitTGA/CMakeFiles/TGA_Lib.dir/src/TGA_Lib.cc.i
.PHONY : src/TGA_Lib.cc.i

src/TGA_Lib.s: src/TGA_Lib.cc.s

.PHONY : src/TGA_Lib.s

# target to generate assembly for a file
src/TGA_Lib.cc.s:
	cd /home/matthias/Documents/cpp/bit-nes && $(MAKE) -f bitTGA/CMakeFiles/TGA_Lib.dir/build.make bitTGA/CMakeFiles/TGA_Lib.dir/src/TGA_Lib.cc.s
.PHONY : src/TGA_Lib.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... TGA_Lib"
	@echo "... edit_cache"
	@echo "... src/TGA_Lib.o"
	@echo "... src/TGA_Lib.i"
	@echo "... src/TGA_Lib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/matthias/Documents/cpp/bit-nes && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

